### ISSUE TITLE
Screenshot of your phone homescreen

### ISSUE THREAD

**Issue by AchoArnold** [olpeh/ama#1]

**Comment by olpeh** [comment]
Hey @AchoArnold! I'm super sorry for this late response! I don't know why I haven't got a notification about this question:

![photo5868370110840940852](https://cloud.githubusercontent.com/assets/6113341/26598707/ce8a16c0-457e-11e7-9d7d-26c878bf20be.jpg)

Some notes/explanations if you are interested:
- Device: OnePlus 3T
- Fenix is a Twitter client I use
- The weird color tint comes from [Twilight](https://play.google.com/store/apps/details?id=com.urbandroid.lux)
- The launcher I use is [Z-launcher](https://play.google.com/store/apps/details?id=com.nokia.z)
- devRant is awesome
- Using freedome VPN

**Comment by olpeh** [comment]
**Edit:** This is how my current home screen looks like. Switched to Sony Xperia X running SailfishOS :sunglasses: 

![screenshot_20171031_002_edit](https://user-images.githubusercontent.com/6113341/32209626-ca82cf8e-be11-11e7-9d59-49edcc25c739.png)
